generators/urls.py
from django.urls import path
from .views import GeneratorListView, GeneratorStepsView

app_name = 'generator'
urlpatterns = [
    path('', GeneratorListView.as_view(), name='generator_list'),
    path('<slug>/', GeneratorStepsView.as_view(), name='generator_steps')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('generators/', include('generators.urls'))
]

generators/models.py
from django.db import models


text = 'text'
email = 'email'
file_field = 'file'

FIELDS_CHOICES = (
    (text, 'text'),
    (email, 'email'),
    (file_field, 'file')
)


class Generator(models.Model):
    template_name = models.CharField(max_length=150)
    identifier = models.CharField(max_length=150)
    slug = models.SlugField(max_length=150)
    preview = models.ImageField(upload_to='images/', null=True, blank=True)
    image_one = models.ImageField(upload_to='images/%y/%m', null=True, blank=True)
    image_two = models.ImageField(upload_to='images/%y/%m', null=True, blank=True)
    image_three = models.ImageField(upload_to='images/%y/%m', null=True, blank=True)
    image_four = models.ImageField(upload_to='images/%y/%m', null=True, blank=True)
    name = models.CharField(max_length=150)
    icon = models.ImageField(upload_to='icons/')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description_title = models.CharField(max_length=150)
    description = models.TextField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Step(models.Model):
    generator = models.ForeignKey(Generator, related_name='steps', on_delete=models.CASCADE)
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class Field(models.Model):
    step = models.ForeignKey(Step, related_name='fields', on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    placeholder = models.CharField(max_length=100)
    input_name = models.CharField(max_length=100)
    field = models.CharField(choices=FIELDS_CHOICES, max_length=30)
    require = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class FieldData(models.Model):
    data = models.JSONField()

generators/forms.py
from django import forms
from .models import Field, FieldData


class FieldForm(forms.Form):
    data = forms.CharField(max_length=255)


class FieldDataForm(forms.ModelForm):
    class Meta:
        model = FieldData
        fields = ['data']

generators/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, CreateView
from .models import Generator, Step, Field, FieldData
from .forms import FieldDataForm, FieldForm, forms
import json


class GeneratorListView(ListView):
    model = Generator
    template_name = 'generators/index.html'


class GeneratorStepsView(ListView):
    template_name = 'generators/steps_list.html'
    queryset = Field.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        generator = get_object_or_404(Generator, slug=self.kwargs['slug'])
        context = super(GeneratorStepsView, self).get_context_data(**kwargs)
        context['steps'] = Step.objects.filter(generator=generator)
        return context

    def post(self, request, slug):
        jsin = json.dumps(request.POST)
        FieldData.objects.create(data=jsin)
        return redirect('generator:generator_list')

generators/templates/generators/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for generator in object_list %}
        <a href="{% url 'generator:generator_steps' generator.slug %}"><h4>{{ generator.name }}</h4></a>
    {% endfor %}
</body>
</html>

generators/templates/generators/steps_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="." method="post">
 {% for step in steps %}
    {{ step.name }}<br>
    {% with field=step.fields.get %}<br>
 <div class="field">
         {% csrf_token %}
        {{ field.name }}<br>
        {{ field.input_name }}<br>
     <input type="{{ field.field }}" placeholder="{{ field.placeholder }}" name="{{ field.name }}">
 </div>
 <br>
    {% endwith %}

 {% endfor %}
    <button type="submit" >submit</button>
</form>

</body>
</html>